apiVersion: v1
kind: Pod
metadata:
  name: no-resource-limits-demo
  namespace: secure-demo
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - name: no-limits
      image: 000000000000.dkr.ecr.us-east-1.amazonaws.com/aws-eks-secure-delivery-detection-lab-dev-api:placeholder
      securityContext:
        runAsUser: 10001
        privileged: false
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
