apiVersion: v1
kind: Pod
metadata:
  name: root-container-demo
  namespace: secure-demo
spec:
  securityContext:
    runAsNonRoot: false
  containers:
    - name: root
      image: 000000000000.dkr.ecr.us-east-1.amazonaws.com/aws-eks-secure-delivery-detection-lab-dev-api:placeholder
      securityContext:
        runAsUser: 0
        privileged: false
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
