apiVersion: v1
kind: Pod
metadata:
  name: wrong-registry-demo
  namespace: secure-demo
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - name: wrong-registry
      image: docker.io/library/nginx:latest
      securityContext:
        runAsUser: 10001
        privileged: false
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
