apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-ecr-images
  annotations:
    policies.kyverno.io/title: Require Amazon ECR Images
    policies.kyverno.io/category: Supply Chain Security
    policies.kyverno.io/severity: high
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: containers-from-ecr
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Container images must come from a private Amazon ECR registry."
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                any:
                  - key: "{{ regex_match('^[0-9]{12}\\.dkr\\.ecr\\.[a-z0-9-]+\\.amazonaws\\.com/.+', element.image) }}"
                    operator: Equals
                    value: false
