apiVersion: v1
kind: Namespace
metadata:
  name: secure-demo
  labels:
    app.kubernetes.io/name: secure-demo
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
