apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: secure-demo-default-deny
  namespace: secure-demo
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: secure-demo-api-ingress
  namespace: secure-demo
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: secure-demo
    matchExpressions:
      - key: quarantine
        operator: NotIn
        values:
          - "true"
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: secure-demo-dns-and-egress
  namespace: secure-demo
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: secure-demo
    matchExpressions:
      - key: quarantine
        operator: NotIn
        values:
          - "true"
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 169.254.169.254/32
      ports:
        - protocol: TCP
          port: 443
