apiVersion: v1
kind: ServiceAccount
metadata:
  name: secure-demo-sa
  namespace: secure-demo
  labels:
    app.kubernetes.io/name: secure-demo
  annotations:
    eks.amazonaws.com/role-arn: APP_IRSA_ROLE_ARN_PLACEHOLDER
automountServiceAccountToken: false
