name: Terraform Security & Plan

on:
  pull_request:
    paths:
      - 'terraform/**'
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

permissions:
  id-token: write
  contents: read
  security-events: write

env:
  TF_VAR_alert_email: ${{ secrets.ALERT_EMAIL }}

jobs:
  terraform-checks:
    name: Terraform Security and Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/envs/dev
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ff717079ee2060e4bcee96c4779b553acc87447c # v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/aws-eks-secure-delivery-detection-lab-dev-github-actions
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3

      - name: Write Backend Config
        run: |
          ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
          cat > backend.hcl <<EOF
          bucket         = "eks-sec-delivery-dev-tfstate-${ACCOUNT_ID}"
          key            = "dev/terraform.tfstate"
          region         = "us-east-1"
          dynamodb_table = "aws-eks-secure-delivery-detection-lab-dev-tf-locks"
          encrypt        = true
          EOF

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive ../../

      - name: Terraform Init
        id: init
        run: terraform init -backend-config=backend.hcl

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Run Checkov Security Scan
        uses: bridgecrewio/checkov-action@99bb2caf247dfd9f03cf984373bc6043d4e32ebf # v12.1347.0
        with:
          directory: terraform/
          framework: terraform
          output_format: cli,sarif
          output_file_path: console,results.sarif
          skip_check: CKV_AWS_18,CKV_AWS_109,CKV_AWS_111,CKV_AWS_144,CKV_AWS_274,CKV_AWS_356,CKV_TF_1,CKV_TF_2,CKV2_AWS_56,CKV2_AWS_62,CKV2_AWS_64 # Skips for lab environment allowed permissions, KMS key-policy wildcards, and low-value S3 lab controls

      - name: Upload Checkov SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@78ed0c7291d93e40c51b085850dc669a4c3ab73b # v3
        with:
          sarif_file: results.sarif
          category: checkov

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        id: plan
        run: terraform plan -no-color
